### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by pijey** [Motokaptia/ember-cli-prerender#2]
When creating a new project and installing ember-cli-prerender, I get the following errors : 
First, when running npm run build : 
`
The input directory 'dist/fastboot' does not exist.
Error: The input directory 'dist/fastboot' does not exist.
    at err (/home/user/Dev/testprerender/node_modules/ember-cli-prerender/lib/tasks/prerender.js:87:13)
    at Class.run (/home/user/Dev/testprerender/node_modules/ember-cli-prerender/lib/commands/prerender.js:18:64)
...
`

I had to upgrade ember-cli-fastboot to the version 1.0.0-rc.5 and fastboot to 1.0.0-rc.7 to make it go away.

Then when I run npm run build : 

`
Couldn't find /home/user/Dev/testprerender/dist/package.json. You may need to update your version of ember-cli-fastboot.
Error: Couldn't find /home/user/Dev/testprerender/dist/package.json. You may need to update your version of ember-cli-fastboot.
    at EmberApp.readPackageJSON (/home/user/Dev/testprerender/node_modules/fastboot/src/
...
`

This error keeps happening and the build never ends...

Any idea ?

Thanks

**Comment by pijey** [comment]
I'm running : 
ember-cli: 2.13.3
node: 6.9.2
os: linux x64

**Comment by ardalann** [comment]
@rbezemer Could you look into this please?

**Comment by rbezemer** [comment]
Hi, sorry for the delay in noticing this, I'll have a look at this and see what's going on with the build

**Comment by jpsilvashy** [comment]
Hmm, I also have this same issue. I'll see if I can sort it out.

**Comment by rbezemer** [comment]
Thanks, I've just ran out of time to have a look at this.

**Comment by rbezemer** [comment]
Finally had time to have a look at this, I managed to solve the issue by running
`ember install ember-cli-fastboot` looks like there might be a missing dependency in the include list somewhere.

**Comment by rbezemer** [comment]
Updated to new version of ember fastboot and fixed errors
